### ISSUE TITLE
DecryptAndVerify

### ISSUE THREAD

**Issue by joserrasb** [Cinchoo/ChoPGP#2]
Hi,
How can I decrypt a file that was encrypted with EncryptFileAndSign method? 

Is there a method to decrypt and verify a file? After I encrypt a file with EncryptFileAndSign method I cannot decrypt it with Decrypt method I got the execption:  "Encrypted message contains a signed message - not literal data."

Thank you!! Great work with the library.

**Comment by Cinchoo** [comment]
Hi, put a fix to DecryptFile to handle files encrypt with EncryptFileNSign method.

Also added new method DecryptFileNVerify as well to verify the file before decrypt it,
