### ISSUE TITLE
Use streaming for inputs to EncryptFileAndSign and EncryptFile

### ISSUE THREAD

**Issue by jaffadan** [Cinchoo/ChoPGP#6]
Started to use your API and so for really found it useful.   So i was wondering if in your plans you where planning on using Streaming to replace file access in both EncryptFileAndSign and EncryptFile. (I am sure i would want decrypt as well but in my current project i do not need it)

**Comment by jaffadan** [comment]
I just saw the new version with the new methods.  Can't wait to change my code to test it out.  

Thank You very much.

**Comment by jaffadan** [comment]
I did not mean to close the enhancement.  Sorry

**Comment by Cinchoo** [comment]
Yes, there are new methods added to support streaming capabilities. Try it and let me know.

**Comment by jaffadan** [comment]
Worked like a champ, thank you very much.
