### ISSUE TITLE
EncryptAndSign methods Outputstream does not seem to return the encrypted Stream of the inputstream

### ISSUE THREAD

**Issue by jaffadan** [Cinchoo/ChoPGP#7]
Using the new Streaming methods seem to work for decryption but encryption all files seem to become 
1 k files.  I reverted my code back to using file based encryption (Which worked file)  

Code:

using Cinchoo.PGP;
using Microsoft.Azure.KeyVault;
using Microsoft.Azure.KeyVault.Models;
using Microsoft.Azure.Services.AppAuthentication;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.IO;

namespace AzureERPFileEncryption
{
    class Utils
    {
        internal static async System.Threading.Tasks.Task<Stream> CopyKeysAsync(string key, string keyContainer)
        {
            Stream keyStream = new MemoryStream();
            if (CloudStorageAccount.TryParse(Environment.GetEnvironmentVariable("AzureWebJobsStorage"), out CloudStorageAccount storageAccount))
            {
                var cloudBlobClient = storageAccount.CreateCloudBlobClient();
                CloudBlobContainer cloudBlobContainer = cloudBlobClient.GetContainerReference(keyContainer + "/");

                CloudBlockBlob blockBlob = cloudBlobContainer.GetBlockBlobReference(key);
            
                await blockBlob.DownloadToStreamAsync(keyStream);
            }
            return keyStream;
        }

        internal static async System.Threading.Tasks.Task<Stream> DecryptBlobAsync(Stream myBlob, string name, string source, String functionDirectory, TraceWriter log)
        {
            if (myBlob == null)
            {
                throw new ArgumentNullException(nameof(myBlob));
            }

            bool sign = false;
            string publicKey = null;
            string privateKey = null;
            string passPhrase = null;
            switch (source.ToLower())
            {
                /*
                 *  Long term this data should be loaded into a database or a Config file 
                 * 
                 * 
                 */ 
                case "one":
                    publicKey = Environment.GetEnvironmentVariable("onePublicKey");
                    privateKey = Environment.GetEnvironmentVariable("oneAcostaPrivate");
                    sign = true;
                    break;
                case "two":                 
                    privateKey = Environment.GetEnvironmentVariable("twoAcostaPrivate");
                    passPhrase = await GetSecertValue(Environment.GetEnvironmentVariable("twoPassphrase"));
                    sign = false;
                    break;
                case "three":                    
                    privateKey = Environment.GetEnvironmentVariable("wageworksAcostaPrivate");
                    passPhrase = await GetSecertValue(Environment.GetEnvironmentVariable("threePassphrase"));
                    sign = false;
                    break;
                default:
                    break;
            }

            Stream decryptStream = new MemoryStream();        
            try
            {                                
                if (sign)
                {
                    using (ChoPGPEncryptDecrypt pgp = new ChoPGPEncryptDecrypt())
                    using (Stream privateStream = CopyKeysAsync(privateKey, Environment.GetEnvironmentVariable("privatekeyscontainer")).Result)
                    using (Stream publicStream = CopyKeysAsync(publicKey, Environment.GetEnvironmentVariable("publickeyscontainer")).Result)

                    {
                        privateStream.Seek(0, SeekOrigin.Begin);
                        publicStream.Seek(0, SeekOrigin.Begin);
                        pgp.DecryptAndVerify(myBlob, decryptStream, publicStream, privateStream, passPhrase);
                    }
                    }
                    else
                    {
                    using (ChoPGPEncryptDecrypt pgp = new ChoPGPEncryptDecrypt())
                    using (Stream privateStream = CopyKeysAsync(privateKey, Environment.GetEnvironmentVariable("privatekeyscontainer")).Result)
                        {
                        privateStream.Seek(0, SeekOrigin.Begin);
                       
                        pgp.Decrypt(myBlob, decryptStream, privateStream, passPhrase);
                        }
                    }                
            }
            catch (Exception ex)
            {
                log.Error("Error in DecryptBlobAsync", ex.InnerException);
                log.Error("Error in DecryptBlobAsync " + ex.Message);
                log.Error("Error in DecryptBlobAsync" + ex.StackTrace);
                throw ex;
            }
            return decryptStream;
        }

        internal static async System.Threading.Tasks.Task<MemoryStream> SignAndEncryptBlobAsync(Stream myBlob, string name, string source, string functionDirectory, TraceWriter log)
        {

            bool sign = false;
            bool armor = true;
            bool withIntegrityCheck = false;
            string publicKey = null;
            string privateKey = null;
            string passPhrase = null;
            MemoryStream encryptedStream = new MemoryStream();
                switch (source.ToLower())
            {
                case "adp":
                    publicKey = Environment.GetEnvironmentVariable("sfd");
                    privateKey = Environment.GetEnvironmentVariable("asf");
                    passPhrase = await GetSecertValue(Environment.GetEnvironmentVariable("asf"));
                    sign = true;
                    armor = true;
                    withIntegrityCheck = false;
                    break;
                case "kronos":
                    publicKey = Environment.GetEnvironmentVariable("kronos");
                    sign = false;
                    break;
                default:
                    break;
            }
            
            
                try
                {
                    if (sign)
                    {
                        using (ChoPGPEncryptDecrypt pgp = new ChoPGPEncryptDecrypt())
                        using (Stream publicStream = CopyKeysAsync(publicKey, Environment.GetEnvironmentVariable("publickeyscontainer")).Result)
                        using (Stream privateStream = CopyKeysAsync(privateKey, Environment.GetEnvironmentVariable("privatekeyscontainer")).Result)
                        {
                            privateStream.Seek(0, SeekOrigin.Begin);
                            publicStream.Seek(0, SeekOrigin.Begin);
                            pgp.EncryptAndSign(myBlob, encryptedStream, publicStream, privateStream, passPhrase, armor, withIntegrityCheck);
                        }
                    }
                    else
                    {
                        using (ChoPGPEncryptDecrypt pgp = new ChoPGPEncryptDecrypt())
                        using (Stream publicStream = CopyKeysAsync(publicKey, Environment.GetEnvironmentVariable("publickeyscontainer")).Result)
                        {
                            publicStream.Seek(0, SeekOrigin.Begin);
                            pgp.Encrypt(myBlob, encryptedStream, publicStream, armor, withIntegrityCheck);
                        }
                    }
                }
                catch (Exception ex)
                {
                    log.Error("Error in SignAndEncryptBlobAsync", ex.InnerException);
                    throw ex;
                }
                return encryptedStream;          
        }                         
    

        internal static async System.Threading.Tasks.Task<string> GetSecertValue(string value)
        {
            try
            {
                var secretUri = SecretUri(value);
                var serviceTokenProvider = new AzureServiceTokenProvider();
                var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(serviceTokenProvider.KeyVaultTokenCallback));
                SecretBundle secretValue = await keyVaultClient.GetSecretAsync(secretUri);
                return secretValue.Value;
            }
            catch (Exception ex)
            {                
                throw ex;
            }
        }

        public static string SecretUri(string secret)
        {
            return $"{Environment.GetEnvironmentVariable("KeyVaultUri")}/Secrets/{secret}";
        }
    }
}

**Comment by Cinchoo** [comment]
Not able to reproduce it, Can u please try yourself with sample test code? let me know.
